version: '3.9'

services:
  python-app:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: python-app
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kochamadb
      POSTGRES_DB: gios_data
    ports:
      - "5000:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:
